name: Generate PlantUML Diagrams
on:
  push:
    paths:
      - '**.puml'
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".puml"
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2

      - name: Generate SVG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tsvg *${{ env.UML_FILES }}            

      - name: Get changed UML files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree -r --no-commit-id --name-only ${{ github.sha }} | grep ${{ env.UML_FILES }} | xargs)"

      - name: UML files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - name: Generate PNG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tpng *${{ env.UML_FILES }}

      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.6 
        with: 
          file_pattern: *.png *.svg
          commit_message: "Auto Generate SVG and PNG images for PlantUML diagrams" 
          #branch: ${{ github.head_ref }}